### ISSUE TITLE
https://api.cloud.nabto.com/dashboard/ 401 Unauthorized

### ISSUE THREAD

**Issue by tlk** [nabto/nabto-webhook-demo#1]
Out of curiosity I clicked https://api.cloud.nabto.com/dashboard/ only to receive a "401 Unauthorized". 

Perhaps the error message could be hinting at how to signup / login correctly?

**Comment by fusionfoxy** [comment]
Link error fixed in README

**Comment by gammelby** [comment]
@tlk you need to stop by HQ for a beer and a general recap some day :-)
